hub:
   port: 4444
   remoteControlPollingIntervalInSeconds: 180
   sessionMaxIdleTimeInSeconds: 300
   environments:
       - name:    "*firefox"
         browser: "*firefox"
       - name:    "*chrome"
         browser: "*chrome"
       - name:    "*iexplore"
         browser: "*iexplore"
       - name:    "*iehta"
         browser: "*iehta"
